### ISSUE TITLE
多图压缩有bug

### ISSUE THREAD

**Issue by zhangfeng86911** [shaohui10086/AdvancedLuban#19]
多图压缩返回的文件列表中有文件重复

**Comment by shaohui10086** [comment]
@zhangfeng86911 方便提供一下版本号，以及调用方式吗？

**Comment by TopTime1** [comment]
E/AndroidRuntime: FATAL EXCEPTION: RxComputationScheduler-3
                  Process: com.ikongjian.worker, PID: 12642
                  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: java.lang.OutOfMemoryError: Failed to allocate a 3244812 byte allocation with 2117648 free bytes and 2MB until OOM
                      at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                      at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                      at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:639)
                      at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:615)
                      at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:391)
                      at me.shaohui.advancedluban.Luban.compress(Luban.java:585)
                      at me.shaohui.advancedluban.Luban.compress(Luban.java:629)
                      at me.shaohui.advancedluban.Luban.customCompress(Luban.java:502)
                      at me.shaohui.advancedluban.Luban.compressImage(Luban.java:357)
                      at me.shaohui.advancedluban.Luban.access$200(Luban.java:42)
                      at me.shaohui.advancedluban.Luban$9.call(Luban.java:218)
                      at me.shaohui.advancedluban.Luban$9.call(Luban.java:215)
                      at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
                      at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
                      at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
                      at rx.Subscriber.setProducer(Subscriber.java:211)
                      at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
                      at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
                      at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
                      at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
                      at rx.Observable.unsafeSubscribe(Observable.java:10200)
                      at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                      at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                      at rx.Observable.unsafeSubscribe(Observable.java:10200)
                      at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                      at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$1.call(EventLoopsScheduler.java:172)
                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) 
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                      at java.lang.Thread.run(Thread.java:818) 

多图压缩，遇到内存溢出，求解决！

**Comment by shaohui10086** [comment]
换用最新版1.3.1，压缩模式选用CUSTOM_GEAR可以有效避免OOM的问题，还会再解决

**Comment by TopTime1** [comment]
好的我试试
